title: 'Flextype'
description: 'Modern Open Source Flat-File Content Management System'
author:
  name: ''
  email: ''
timezone: UTC
charset: UTF-8
date_format: 'F d Y H:i:s'
theme: default
locale: en
entries:
  main: home
  error404:
    title: 'Error 404'
    description: 'We''re sorry but the page you are looking for doesn''t appear to exist!'
    content: 'We''re sorry but the page you are looking for doesn''t appear to exist!'
    template: default
errors:
  display: false
cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
accept_file_types:
  - gif
  - jpg
  - jpeg
  - png
  - ico
  - zip
  - tgz
  - txt
  - md
  - doc
  - docx
  - pdf
  - epub
  - xls
  - xlsx
  - ppt
  - pptx
  - mp3
  - ogg
  - wav
  - m4a
  - mp4
  - m4v
  - ogv
  - wmv
  - avi
  - webm
  - svg
keywords: 'flextype, php, cms, flat-file cms, flat cms, flatfile cms, html'
robots: 'index, follow'
