#
# Site configuration
#

title: "Flextype"
description: "Modern Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
date_format: "F d Y H:i:s."
charset: UTF-8

theme: default

plugins:

locale: "en"
locales: [en]

pages:
  flush_cache: false
  main: home

errors:
  display: true

cache:
  enabled: false
  prefix: flextype
  driver: auto
  lifetime: 604800
